server.port=8081

spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/?ssl=true&replicaSet=${MONGO_REPLICA_SET}&authSource=${MONGO_AUTH_SOURCE}&appName=${MONGO_APP_NAME}
spring.data.mongodb.database=${MONGO_DATABASE}

# Eureka client configuration
eureka.client.service-url.defaultZone=https://fitness-activity-eureka.onrender.com/eureka/
eureka.instance.hostname=fitness-activity-activityservice.onrender.com
eureka.instance.prefer-ip-address=false

# RabbitMQ configuration
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST}
spring.rabbitmq.ssl.enabled=true
rabbitmq.exchange.name=${RABBITMQ_EXCHANGE_NAME}
rabbitmq.queue.name=${RABBITMQ_QUEUE_NAME}
rabbitmq.routing.key=${RABBITMQ_ROUTING_KEY}
