server.port=8082

spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/?ssl=true&replicaSet=${MONGO_REPLICA_SET}&authSource=${MONGO_AUTH_SOURCE}&appName=${MONGO_APP_NAME}
spring.data.mongodb.database=${MONGO_DATABASE}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#amqps://iglbeqar:UkCYCOsgwjD7xeBuSnVZy2YtGtzdR5Lb@mustang.rmq.cloudamqp.com/iglbeqar
# RabbitMQ configuration
spring.rabbitmq.host=mustang.rmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=iglbeqar
spring.rabbitmq.password=UkCYCOsgwjD7xeBuSnVZy2YtGtzdR5Lb
spring.rabbitmq.virtual-host=iglbeqar
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.default-requeue-rejected=false
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking

#Google gemini configuration
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.project-id=${GEMINI_PROJECT_ID}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
