server.port=8083

# Database configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Eureka client configuration
eureka.client.service-url.defaultZone=https://fitness-activity-eureka.onrender.com/eureka/
eureka.instance.hostname=fitness-activity-userservice.onrender.com
eureka.instance.prefer-ip-address=false
